version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: ['uvicorn', 'api:app', '--host', '0.0.0.0', '--port', '8080', '--reload']

  frontend:
    build: ./frontend
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm start"
